const PROBLEM_IN_GET_LIST_OF_BLOG = "مشکلی در گرفتن لیست بلاگ خا به وجود آمد",
    PROBLEM_IN_GET_BLOG = "مشکل در ردیافت بلاگ",
    PROBLEM_IN_CREATE_BLOG = "مشکل در ساخت بلاگ",
    SUCCESS_IN_CREATE_BLOG = "بلاگ با موفقیت ساخته شد",
    SUCCESS_IN_CREATE_PORTFOLIO = "پورتفولیو با موفقیت ساخته شد",
    SUCCESS_IN_UPLOAD_IMAGE = "تص.یر با وفقیت ذخیره شد",
    BLOG_LIST_NOT_FOUND = "لیست بلاگ پیدا نشد",
    PLEASE_INSERT_IMAGE = "لطفا تصویر را انتخاب کنید",
    PROBLEM_IN_GETTING_BLOG = "مشکل در دریافت لیست مطالب",
    REPEATED_TITLE = "عنوان تکراریست",
    SOME_PROBLEM_HAPPEND = "مشکلی پیش آمد",
    PORTFOLIO_NOT_FOUND = "پورتفولیو یافت نشد",
    REPEATED_SLUG = "slug تکراریست",
    BLOG_NOT_FOUND = "بلاگی یافت نشد",
    PROBLEM_IN_GETTING_PORTFOLIOS = "مشکلی در دریافت پورتفولیو ها به وجود آمد",
    PROBLEM_IN_GETTING_PORTFOLIO = "مشکلی در دریافت پورتفولیو  به وجود آمد",
    OK = "Ok";

export {
    PROBLEM_IN_GET_LIST_OF_BLOG,
    SUCCESS_IN_UPLOAD_IMAGE,
    PROBLEM_IN_CREATE_BLOG,
    SUCCESS_IN_CREATE_BLOG,
    PROBLEM_IN_GET_BLOG,
    BLOG_LIST_NOT_FOUND,
    PLEASE_INSERT_IMAGE,
    BLOG_NOT_FOUND,
    SOME_PROBLEM_HAPPEND,
    REPEATED_TITLE,
    SUCCESS_IN_CREATE_PORTFOLIO,
    REPEATED_SLUG,
    PROBLEM_IN_GETTING_PORTFOLIOS,
    PROBLEM_IN_GETTING_PORTFOLIO,
    PORTFOLIO_NOT_FOUND,
    PROBLEM_IN_GETTING_BLOG,
    OK,
};
